let num = 5;
console.log(typeof num);
let bul = true;
console.log(typeof bul);
let bigint = 999999999999999n;
console.log(typeof bigint);
let string = "Hello";
console.log(typeof string);
let nol = null;
console.log(typeof nol);
let undef = undefined;
console.log(typeof undef);
let object = {};
console.log(typeof object);
let symbol = Symbol();
console.log(typeof symbol);
let function1 = function () {};
console.log(typeof function1);
let array = [];
console.log(typeof array);
